lib: Don't use variable length arrays in osa_data_read_out structure
Clang does not support variable length arrays in structures and
reports the following error:

  lib/diag.c:2059:12: error: fields must have a constant size: 'variable
                             length array in structure' extension will never
			     be supported
          uint32_t entry_dwords[osa_data_entries_out.entries_remaining * 6];

To fix the error without too much refactoring, switch to using alloca()
instead.