Fix missing static sparse warning
cli/main.c:44:32: error: symbol 'empty_opts' was not declared. Should it be static?
cli/main.c:46:22: error: symbol 'global_dev' was not declared. Should it be static?