build: Fix ncurses static linking issue
Static linking of ncurses library now requires a new define
-DNCURSES_STATIC, otherwise linking errors like below would show up.

undefined reference to `__imp_acs_map'